name: DevSecOps End to End pipeline

on: 
    push:
        branches:
            - master

jobs:
    code-quality:
        uses: ./.github/workflows/code-quality.yml
    
    secrets-scan:
        uses: ./.github/workflows/secret-scan.yml

    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml

    docker-scan:
        uses: ./.github/workflows/docker-lint.yml

    build-push:
        needs: [code-quality, secrets-scan, dependency-scan , docker-scan]
        uses: ./.github/workflows/build-push.yml
        secrets: inherit
    trivy:
        needs: [build-push]
        uses: ./.github/workflows/image-scan.yml
        secrets: inherit
    deploy:
        needs: [trivy]
        uses: ./.github/workflows/deploy.yml
        secrets: inherit
    