# Scan the Docker file for issues & CVES
name: Docker Lint

on: 
    workflow_call:

jobs:
    validate-dockerfile:
        runs-on: ubuntu-latest

        steps:
            - name: check code
              uses: actions/checkout@v4

            - name: Validate DockerFile
              uses: hadolint/hadolint-action@v3.1.0
              with: 
                dockerfile: Dockerfile