# API keys, sensitive data, credentials
# GitLeaks
name: Secrets Scan

on: 
    workflow_call:

jobs:
    secrets-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4
              with: 
                fetch-depth: 0
# fetch depth 0 means fetching the older code and further checking for gitleaks
# if we donot use that i will only fetch in the latest code but secruity leakage can be previous also
            - name: Run Git Leaks Scanner
              uses: gitleaks/gitleaks-action@v2
              
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this is required for accessing the code and github automatically manages this 